### ISSUE TITLE
Ideas?

### ISSUE THREAD

**Issue by myobie** [myobie/buzz#1]
Please contribute ideas here. This is a public discussion.

**Comment by daniel-marschner** [comment]
In general I really like that idea and will be up for contributing to it in the future. :)

**Comment by chad** [comment]
I would like an API that would give me data about every failure of a certain kind. Specifically I want to be able to say "give me the HTTP parameters sent during the last 10 failures on this REST endpoint" as an example.  Would be helpful for more quickly automating troubleshooting of issues against production data.
